name: Deploy to Private Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: mvn-build-docker-build-push
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2 # build-push-action 사용
      with:
        context: .
        push: true
        tags: lundaljung/demo-ci-cd-backend:latest
        cache-from: type=gha # 여기서 gha 는 Guthub Actions 용 캐시를 의미합니다.
        cache-to: type=gha,mode=max
    
    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: "ap-northeast-2"
  
    # - name: Start Auto Scaling Instance Refresh
    #   run: |
    #     aws autoscaling start-instance-refresh --auto-scaling-group-name back_asg